site_name: Amy's Docs
site_url: https://amyy.me/docs
theme:
  name: amyy-theme
  fit_to_height: true

nav:
  - Blogs: 'blogs/index.md'
  - CTFs: 'ctfs/index.md'
  - Development: 'development/index.md'
  - OS Configuration: 'osconfig/index.md'
  - Software: 'software/index.md'
