site_name: Amy's Documentation
site_url: https://amyy.me/docs
theme:
  name: terminal
  palette: pink
  features:
    - navigation.side.indexes
    - revision.date
plugins:
  - search
  - git-revision-date
markdown_extensions:
  - toc:
      baselevel: "7"
      toc_depth: "7"
nav:
  - Blogs:
    - Universal Formatter: 'blogs/uformat.md'
    - SRC Analyzer Rewrite: 'blogs/analyzer.md'
  - CTFs:
    - NCL Spring 2025 Team Game: 'ctfs/ncl-spring-2025-team.md'
    - THM Industrial Intrusion: 'ctfs/thm-industrial-intrusion.md'
  - Development:
    - N64/Wii Toolchains: 'development/n64-wii.md'
  - OS Configuration:
    - Resize Linux Partition: 'osconfig/resizelinux.md'
  - Software:
    - LiveSplit on macOS/Linux: 'software/livesplit.md'
